DROP function IF EXISTS `DaysInThisYear`;

DELIMITER $$
CREATE DEFINER=`root`@`127.0.0.1` FUNCTION `DaysInThisYear`(addNum INT(11)) RETURNS int(11)
    DETERMINISTIC
BEGIN

	RETURN addNum + DAYOFYEAR(
		LAST_DAY(DATE_ADD(NOW(), INTERVAL 12-MONTH(NOW()) MONTH))
	); 
    
END$$

DELIMITER ;

