DROP function IF EXISTS `SPLIT_EMAIL_IN_WORDS`;

DELIMITER $$
CREATE DEFINER=`bit8_admin`@`127.0.0.1` FUNCTION `SPLIT_EMAIL_IN_WORDS`(toSplit VARCHAR(250), everyNChar INT, delim VARCHAR(2)) RETURNS varchar(255) CHARSET utf8
BEGIN
 
 RETURN SPLIT_STR_IN_WORDS(SUBSTR(toSplit, 1, GREATEST(LOCATE('@', toSplit)-1, 2)), everyNChar, delim);
 
END$$

DELIMITER ;
